//
// Created by aless on 21/04/2018.
//

#ifndef SMARTFRIDGE_ITPS_IANNE_CARBONARA_BUONAMICO_FILE_H
#define SMARTFRIDGE_ITPS_IANNE_CARBONARA_BUONAMICO_FILE_H

#endif //SMARTFRIDGE_ITPS_IANNE_CARBONARA_BUONAMICO_FILE_H

int createNewFile(char nome[]);
int searchOnFile(char word[]);